version: "3"
services:
  building:
    build:
      context: ./building
      dockerfile: Dockerfile_build
      volumes:
        - ./:/home/ubuntu/boxfuse-sample-java-war-hello/target

  prod:
    build:
      context: ./production
      dockerfile: Dockerfile_prod
      ports:
        - "8080:8080"
      volumes:
        - ./:/usr/local/tomcat/webapps


