version: "3"
services:
  building:
    build:
      context: ./building
      dockerfile: Dockerfile_build
    volumes:
       - ./hello-1.0.war:/home/ubuntu/boxfuse-sample-java-war-hello/target/hello-1.0.war

  prod:
    build:
      context: ./production
      dockerfile: Dockerfile_prod
    ports:
       - "8080:8080"
    volumes:
       - ./hello-1.0.war:/usr/local/tomcat/webapps/hello-1.0.war


