version: "3.8"
services:
  building:
    build:
      context: ./building
      dockerfile: Dockerfile_build
    volumes:
      - vol1:/home/ubuntu/boxfuse-sample-java-war-hello

  prod:
    build:
      context: ./production
      dockerfile: Dockerfile_prod
    ports:
       - "8080:8080"
    volumes:
      - vol1:/usr/local/tomcat/webapps
volumes:
  vol1:

