---
- name: install maven git default-jdk
  hosts: build
  become: yes

  tasks:
    apt:
     name: "{{ packages }}"
     update_cache: yes
    vars:
      packages:
      - maven
      - git
      - default-jdk

- name: upload from git
  hosts: build
  become: yes

  tasks:
    git:
      repo: 'https://github.com/boxfuse/boxfuse-sample-java-war-hello.git'
      dest: /home/ubuntu

- name: build war
  hosts: build
  become: yes

  tasks:
    shell:
      mvn package
    args:
      chdir: /home/ubuntu/boxfuse-sample-java-war-hello