---
- name: build process
  hosts: build
  become: yes
  tasks:
  - name: install maven git default-jdk
    apt:
      update_cache: yes
      pkg:
      - maven
      - git
      - default-jdk

  - name: upload from git project
    git:
      repo: 'https://github.com/boxfuse/boxfuse-sample-java-war-hello.git'
      dest: /home/ubuntu

  - name: build project
    shell:
      mvn package
    args:
      chdir: /home/ubuntu