---
- name: build process
  hosts: build
  become: yes
  tasks:
  - name: install maven git default-jdk
    apt:
      update_cache: yes
      pkg:
      - maven
      - git
      - default-jdk

  - name: upload from git project
    git:
      repo: 'https://github.com/boxfuse/boxfuse-sample-java-war-hello.git'
      dest: /home/ubuntu

  - name: build project
    shell:
      mvn package
    args:
      chdir: /home/ubuntu

  - name: replace war file
    fetch:
      src: /home/ubuntu/target/hello-1.0.war
      dest: /home/black1/Homework


- name: prod process
  hosts: prod
  become: yes
  tasks:
  - name: install tomcat
    apt:
       update_cache: yes
       name: tomcat9
  - name: copy war file
    copy:
        src: /home/black1/Homework/178.154.231.164/home/ubuntu/target/hello-1.0.war
        dest: /var/lib/tomcat9/webapps
