FROM maven:3.6.3-jdk-11
RUN mkdir /home/project
WORKDIR /home/project
RUN git clone https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
RUN chmod +rwx mvn.sh
ADD /home/black1/Homework/mvn.sh /project
ENTRYPOINT ["/home/project/mvn.sh"]
